### PR TITLE
Improving English fonts in SenseHat.jl

### PR DESCRIPTION
**Pull request by NandVinchhi**

### CODE REVIEW

**Comment by aviks** [comment]
Can you do a before and after image of the improvements? For some of the characters at least. You can take photos with your phone and upload.

**Comment by NandVinchhi** [comment]
I actually do not have access to a sensehat. Could I plot on computer and send screenshot?

**Comment by aviks** [comment]
sure

**Comment by NandVinchhi** [comment]
This is examples of a few characters that I edited.
left - before
right - after
Screenshot (32)

**Comment by aviks** [comment]
I like the capitals, but the small letters seem to have become too small. I don't think the small letters look worse. Can you revert them? Or may be scale them up.

**Comment by NandVinchhi** [comment]
ok

**Comment by NandVinchhi** [comment]
done.

**Pull request merged**
